In [1]:
#Preamble


import numpy as np


In [4]:
#Question 1: Find equal rows in an array
def findEqual(arr):
    arr=np.array(arr)
    equal_rows = arr[(arr == arr[:, [0]]).all(axis=1)]

    return equal_rows

In [3]:
#Question 1 check
arr=np.array( [ [ 1 , 1 , 1 ] , [ 1 , 2 , 3 ] , [ 2 , 2 , 2 ] ] )
repeats = findEqual(arr)
print(repeats)
#Checks out

[[1 1 1]
 [2 2 2]]


In [8]:
#Question 2: create an 8x8 chess pattern of 1s and 0s using slicing + striding methods

#
board = np.ones((8, 8), dtype=int)
board[1::2, ::2] = 0
board[::2, 1::2] = 0
print(board)


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [27]:
#Question 3: return an array seperated by spaces


def spaceArr(arr): 
    result_array = [" ".join(list(word)) for word in arr]

    return result_array
# Print the result

myarray = np.array(["Hello", "World", "Python"])
myarray2= np.array(["TESTING"])

spaceMyArr= spaceArr(myarray)
spaceMyArr2= spaceArr(myarray2)

print(spaceMyArr)
print(spaceMyArr2)

['H e l l o', 'W o r l d', 'P y t h o n']
['T E S T I N G']


In [18]:
#Question 4: Given a multidimensional matrix, sort the matrix along the columns


# Sort the matrix along its columns
def sortMatrix(arr):
    sorted_matrix = np.sort(arr, axis=0)
    return sorted_matrix
# Print the sorted matrix
matrix = np.array([[3, 2, 1],
                  [6, 5, 4],
                  [9, 8, 7]])
sortedMatrix = sortMatrix(matrix)




print(sortedMatrix)

[[3 2 1]
 [6 5 4]
 [9 8 7]]
